server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flexTechChallenge
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: servlet
spotify:
  client-id: 0c5bb1ce67c645469d73611b372ede04
  client-secret: 9da8e81a16f847f4a988c797435178b1

